export default function Mistake4Page() {
  return (
    <div>
      <h1>Let AI do the coding, and ship it to production</h1>
      <p className="text-muted-foreground mt-2">
        The code generated by AI is not always correct.
      </p>
    </div>
  );
}
